### ISSUE TITLE
row_info

### ISSUE THREAD

**Issue by yakir12** [bramtayl/LightQuery.jl#11]
I know it's there, but for some reason there is no `row_info` for me. Tests pass (they make use of `row_info`) and the version is 0.2.3, but I can't evoke any call with `row_info`:
```
 julia> using LightQuery

julia> row_info
ERROR: UndefVarError: row_info not defined

julia> LightQuery.row_info
ERROR: UndefVarError: row_info not defined
```

**Comment by bramtayl** [comment]
Are you using the dev version? I think last time I versioned `row_info` was called something else. Once I finish SQL support I'll publish a new version.

**Comment by bramtayl** [comment]
New version has `row_info`
